
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '524A182CE4EBF87CAA8568C2439C42A2'
    
_lr_action_items = {'$end':([2,5,],[0,-1,]),'MOT':([4,6,7,],[6,-8,10,]),'(':([0,1,6,7,11,14,15,],[1,4,-8,4,4,-2,-3,]),')':([3,8,9,10,11,12,13,14,15,16,],[5,14,15,-9,-6,-7,-4,-2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'leaf':([7,],[12,]),'head':([4,],[7,]),'S':([1,7,11,],[3,11,11,]),'Sprim':([0,],[2,]),'exprs':([7,11,],[13,16,]),'syntagme':([4,],[8,]),'lexique':([4,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Sprim","S'",1,None,None,None),
  ('Sprim -> ( S )','Sprim',3,'p_axiome','ParserSyntaxer.py',22),
  ('S -> ( syntagme )','S',3,'p_S_1','ParserSyntaxer.py',26),
  ('S -> ( lexique )','S',3,'p_S_2','ParserSyntaxer.py',31),
  ('syntagme -> head exprs','syntagme',2,'p_syntagme','ParserSyntaxer.py',36),
  ('exprs -> S exprs','exprs',2,'p_exprs','ParserSyntaxer.py',42),
  ('exprs -> S','exprs',1,'p_exprs','ParserSyntaxer.py',43),
  ('lexique -> head leaf','lexique',2,'p_lexique','ParserSyntaxer.py',52),
  ('head -> MOT','head',1,'p_head','ParserSyntaxer.py',58),
  ('leaf -> MOT','leaf',1,'p_leaf','ParserSyntaxer.py',64),
]
