
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'RJ\x18,\xe4\xeb\xf8|\xaa\x85h\xc2C\x9cB\xa2'
    
_lr_action_items = {')':([4,5,8,10,11,12,13,14,15,16,],[9,10,15,-2,-7,-9,-4,-6,-3,-5,]),'(':([0,1,6,7,10,14,15,],[1,3,3,-8,-2,3,-3,]),'MOT':([3,6,7,],[7,12,-8,]),'$end':([2,9,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'syntagme':([3,],[5,]),'head':([3,],[6,]),'leaf':([6,],[11,]),'exprs':([6,14,],[13,16,]),'S':([1,6,14,],[4,14,14,]),'lexique':([3,],[8,]),'Sprim':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Sprim","S'",1,None,None,None),
  ('Sprim -> ( S )','Sprim',3,'p_axiome','ParserSyntaxer.py',22),
  ('S -> ( syntagme )','S',3,'p_S_1','ParserSyntaxer.py',26),
  ('S -> ( lexique )','S',3,'p_S_2','ParserSyntaxer.py',31),
  ('syntagme -> head exprs','syntagme',2,'p_syntagme','ParserSyntaxer.py',36),
  ('exprs -> S exprs','exprs',2,'p_exprs','ParserSyntaxer.py',42),
  ('exprs -> S','exprs',1,'p_exprs','ParserSyntaxer.py',43),
  ('lexique -> head leaf','lexique',2,'p_lexique','ParserSyntaxer.py',52),
  ('head -> MOT','head',1,'p_head','ParserSyntaxer.py',58),
  ('leaf -> MOT','leaf',1,'p_leaf','ParserSyntaxer.py',64),
]
